// This program was created by humzah okadia on december 10 2021 
#include <Servo.h>//allows me to control the servos 
Servo sarm1;
Servo sarm2;//the 6 axis of the robotic arm
Servo sarm3;
Servo sarm4;
Servo sarm5;
Servo sarm6;
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/acf1eeb7-c3b0-4f48-a2a9-fd2666b6e5fc 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int servo;
  int motor2;
  int motor4;
  int motor3;
  int arm4;
  int arm6;
  int arm2;
  int arm3;
  int arm1;
  int arm5;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


void setup() {
  // Initialize serial and wait for port to open:
   Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
   delay(1500); 
   sarm1.attach(6);
   sarm2.attach(7);
   sarm3.attach(8);
   sarm4.attach(9);
   sarm5.attach(10);
   sarm6.attach(11);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

void onArm1Change()  {
  // Add your code here to act upon Arm1 change
  sarm1.write(arm1);//when motion is chosen on dashboard write to joint
}

/*
  Since Arm2 is READ_WRITE variable, onArm2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onArm2Change()  {
  // Add your code here to act upon Arm2 change
  sarm2.write(arm2);
}

/*
  Since Arm3 is READ_WRITE variable, onArm3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onArm3Change()  {
  // Add your code here to act upon Arm3 change
  sarm3.write(arm3);
}

/*
  Since Arm4 is READ_WRITE variable, onArm4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onArm4Change()  {
  // Add your code here to act upon Arm4 change
  sarm4.write(arm4);
}

/*
  Since Arm5 is READ_WRITE variable, onArm5Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onArm5Change()  {
  // Add your code here to act upon Arm5 change
  sarm5.write(arm5);
}

/*
  Since Arm6 is READ_WRITE variable, onArm6Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onArm6Change()  {
  // Add your code here to act upon Arm6 change
  sarm6.write(arm6);
}
